services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_rag
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always
  
  app:
    build: .
    container_name: rag_app
    env_file: .env
    environment:
      - QDRANT_URL=http://qdrant:6333
      - HF_HUB_DOWNLOAD_TIMEOUT=60
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    volumes:
      - ./pdf_storage:/app/pdf_storage
      - ./hf_cache:/root/.cache/huggingface
